### ISSUE TITLE
std::thread析构释放的内存没有捕获到，误报内存泄漏

### ISSUE THREAD

**Issue by 511844767** [archibate/mallocvis#2]
如下一段程序
```cxx
#include <iostream>
#include <thread>
#include <chrono>
int main(){
    auto t1 = std::thread([]{
        std::cout << "Hello\n";
    });
    t1.join();
}
```
输出的malloc.html有内存泄漏
![image](https://github.com/archibate/mallocvis/assets/90088954/73c52e66-e63d-42b3-867c-e0222d8dbd04)

**Comment by archibate** [comment]
你是什么操作系统和编译器？我gcc没有遇到这个问题。
而且这里的问题应该是，_IO_deallocate的free被当做了malloc，实际上应该是和_IO_allocate对应上了











无法顺畅的大口呼吸，是活着的最好证明

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月23日(周日) 上午10:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [archibate/mallocvis] std::thread析构释放的内存没有捕获到，误报内存泄漏 (Issue #2)




 
如下一段程序
 #include <iostream&gt; #include <thread&gt; #include <chrono&gt; int main(){     auto t1 = std::thread([]{         std::cout << "Hello\n";     });     t1.join(); }
 
输出的malloc.html有内存泄漏
 image.png (view on web)

**Comment by archibate** [comment]
pull一下吧，现在多线程应该没有问题了。
![图片](https://github.com/archibate/mallocvis/assets/20640597/1a1b927e-e811-4569-858e-b30846359701)

**Comment by 511844767** [comment]
破案了，这是wsl的bug
